[tool.poetry]
name = "aiie"
version = "0.1.0"
description = ""
authors = ["Djalel Benbouzid <djalel@argmax.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.26.0"
watchdog = "^3.0.0"
pandas = "^2.1.0"
plotly = "^5.16.1"
beautifulsoup4 = "^4.12.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.0.287"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
